server:
  port: 8082
  context-path: /ui
  session:
    cookie:
      name: UISESSION

security:
  basic:
    enabled: false
    
oauth2:
  client:
    clientId: ClientId
    clientSecret: secret
    accessTokenUri: http://localhost:8081/auth/oatuh/token
    userAuthorizationUri: http://localhost:8081/auth/oatuh/authorize
  resource:
    userInfoUri: http://localhost:8081/auth/rest/hello/principal
      
spring:
  thymleaf:
    cache: false